# Generated by Django 6.0.7 on 2026-07-11 15:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'modelo de cálculo',
                'verbose_name_plural': 'modelos de cálculo',
                'ordering': ['name', 'version'],
                'indexes': [models.Index(fields=['name'], name='simulations_name_c95f19_idx'), models.Index(fields=['is_active'], name='simulations_is_acti_8a2d80_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('academic_year', models.PositiveIntegerField()),
                ('semester', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Fluid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('density_kg_m3', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('dynamic_viscosity_pa_s', models.DecimalField(decimal_places=8, max_digits=12, validators=[django.core.validators.MinValueValidator(1e-08)])),
                ('reference_temperature_c', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'reference_temperature_c'), name='unique_fluid_temperature_reference')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PROFESSOR', 'Profesor'), ('STUDENT', 'Alumno')], default='STUDENT', max_length=20)),
                ('academic_id', models.CharField(blank=True, max_length=50)),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('COMPLETED', 'Finalizada'), ('WITHDRAWN', 'Retirada')], default='ACTIVE', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='simulations.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'student'), name='unique_student_course_enrollment')],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CALCULATED', 'Calculada'), ('INVALID', 'Inválida'), ('ARCHIVED', 'Archivada')], default='DRAFT', max_length=20)),
                ('diameter_m', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('length_m', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('absolute_roughness_m', models.DecimalField(decimal_places=8, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('velocity_m_s', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('flow_rate_m3_s', models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('gravity_m_s2', models.DecimalField(decimal_places=5, default=Decimal('9.80665'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))])),
                ('density_used_kg_m3', models.DecimalField(decimal_places=3, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('dynamic_viscosity_used_pa_s', models.DecimalField(decimal_places=8, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('reference_temperature_used_c', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True)),
                ('reynolds_number', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('flow_regime', models.CharField(blank=True, choices=[('LAMINAR', 'Laminar'), ('TRANSITION', 'Transicional'), ('TURBULENT', 'Turbulento')], max_length=20, null=True)),
                ('relative_roughness', models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True)),
                ('friction_factor', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('head_loss_m', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('pressure_drop_pa', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('calculation_version', models.CharField(blank=True, max_length=30)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculation_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulations', to='simulations.calculationmodel')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='simulations.course')),
                ('fluid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulations', to='simulations.fluid')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'simulación',
                'verbose_name_plural': 'simulaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner'], name='simulations_owner_i_47d6c1_idx'), models.Index(fields=['created_at'], name='simulations_created_1d715e_idx'), models.Index(fields=['course'], name='simulations_course__bee0fd_idx'), models.Index(fields=['status'], name='simulations_status_54aebc_idx')],
            },
        ),
    ]
