# Generated by Django 6.0.7 on 2026-07-13 01:35

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-academic_year', 'code'], 'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'inscripción', 'verbose_name_plural': 'inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='fluid',
            options={'ordering': ['name'], 'verbose_name': 'fluido', 'verbose_name_plural': 'fluidos'},
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_student_course_enrollment',
        ),
        migrations.AlterField(
            model_name='simulation',
            name='absolute_roughness_m',
            field=models.DecimalField(decimal_places=8, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Rugosidad absoluta [m]'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True, verbose_name='Área [m²]'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='density_used_kg_m3',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Densidad utilizada [kg/m³]'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='diameter_m',
            field=models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Diámetro interno [m]'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='dynamic_viscosity_used_pa_s',
            field=models.DecimalField(decimal_places=8, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Viscosidad dinámica utilizada [Pa·s]'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='flow_rate_m3_s',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Caudal [m³/s]'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='flow_regime',
            field=models.CharField(blank=True, choices=[('LAMINAR', 'Laminar'), ('TRANSITION', 'Transicional'), ('TURBULENT', 'Turbulento')], max_length=20, null=True, verbose_name='Régimen de flujo'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='friction_factor',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Factor de fricción'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='gravity_m_s2',
            field=models.DecimalField(decimal_places=5, default=Decimal('9.80665'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))], verbose_name='Gravedad [m/s²]'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='head_loss_m',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Pérdida de carga [m]'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='length_m',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Longitud [m]'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='pressure_drop_pa',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Caída de presión [Pa]'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='reference_temperature_used_c',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6, verbose_name='Temperatura de referencia utilizada [°C]'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='relative_roughness',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True, verbose_name='Rugosidad relativa'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='reynolds_number',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Número de Reynolds'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='velocity_m_s',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Velocidad [m/s]'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='unique_enrollment_course_student'),
        ),
    ]
