# Generated by Django 6.0.7 on 2026-07-13 13:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_alter_course_options_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='absolute_roughness_m',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Rugosidad absoluta [m]'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='fluid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simulations', to='simulations.fluid'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Longitud [m]'),
        ),
    ]
